---
abstract: 'A Perl binding for LIBLINEAR, a library for classification/regression using linear SVM and logistic regression.'
author:
  - 'Koichi SATOH <sato@seesaa.co.jp>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::Deep: 0
  Test::Exception::LessClever: 0
  Test::LeakTrace: 0
  Test::More: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-LibLinear
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  List::MoreUtils: 0
  Smart::Args: 0
  XSLoader: 0.02
  perl: 5.14.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com/sekia/Algorithm-LibLinear.git
version: 0.12
